name: "CI Basics"

on:
    push: ~
    workflow_dispatch: ~

jobs:
    hello:
        name: "Hello world"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Say hello"
              run: echo "Hello World"
        
    hello2:
        name: "Hello world 2"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Say hello again"
              run: |
                echo "Hello world"
                echo "Hello world"
                exit 1
            - name: "Say Coucou"
              run:
                echo "Coucou"

    hello3:
        needs: ["hello", "hello2"]
        name: "Hello world"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Say hello3"
              run: echo "Hello World 3"
