name: "CI"

on:
    push: 
        paths-ignore: './ci-basics.yml'
    workflow_dispatch: ~

jobs:
    deps:
        name: "install dependancies"
        runs-on: "ubuntu-latest"
        services:
            database:
                image: mysql
                env:
                    MYSQL_ROOT_PASSWORD: password
                    MYSQL_DATABASE: app
                    MYSQL_ROOT_HOST: "%"
                ports:
                    - 3306:3306
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  tools: composer
            - name: "Installation php deps"
              run: |
                export APP_ENV=test
                composer install --prefer-dist --no-interaction --no-progress
            - name: "Check Database healthy"
              run: nc -vz 127.0.0.1 3306 #netcad 
            - name: "Start migrations"
              run: php bin/console d:m:m
              env:
                DATABASE_HOST: '127.0.0.1'
                DATABASE_NAME: 'app'
                DATABASE_PASSWORD: 'password'
            - name: Install Dependencies
              run: composer install
            - name: Run Cs-fixer
              run: php-cs-fixer check src --diff
            - name: Run Unit Tests
              run: php bin/phpunit tests/_1_Unit
            - name: Fonctional Tests
              run: php bin/phpunit tests/_3_Application
            - name: Run PHPStan
              run: php bin/phpstan analyse src --level=max