name: "CI"

on:
    push: 
        paths-ignore: './ci-basics.yml'
    workflow_dispatch: ~

jobs:
    deps:
        name: "install dependancies"
        runs-on: "ubuntu-latest"
        services:
            database:
                image: mysql
                env:
                    MYSQL_ROOT_PASSWORD: password
                    MYSQL_DATABASE: app_test
                    MYSQL_ROOT_HOST: "%"
                ports:
                    - 3306:3306
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  tools: composer
            - name: "Installation php deps"
              run: |
                export APP_ENV=test
                composer install --prefer-dist --no-interaction --no-progress
            - name: "Check Database healthy"
              run: nc -vz 127.0.0.1 3306 #netcad 
            - name: "Start migrations"
              run: php bin/console d:m:m
              env:
                DATABASE_HOST: '127.0.0.1'
                DATABASE_NAME: 'app_test'
                DATABASE_PASSWORD: 'password'
      
    tests-unit:
      name: Unit Tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            tools: composer
        - name: Install Dependencies
          run: composer install
        - name: Run Unit Tests
          run: vendor/bin/phpunit --testsuite=unit

    static-analysis:
      name: Static Analysis
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            tools: composer
        - name: Install Dependencies
          run: composer install
        - name: Run PHPStan
          run: vendor/bin/phpstan analyse src --level=max
